### PR TITLE
navbar, context, 404, livesite updates

### PR DESCRIPTION
**Pull request by Alperdec**
Problem
=======
What problem or issue does this pull request solve [Jira](https://cruzhacks-dev.atlassian.net/jira/software/projects/CRUZ/boards/3/backlog)

Solution
========
Added logic to conditionally render navbars
modified theme context to allow for 'portal theme'. Context now exports object instead of array -- issue with values array is the state within the context is not addressable by name

Updated 404 to function with portal route

added livesite placeholder

Change Summary:
---------------
* Tidy, well formulated commit message
* Another great commit message
* Something else I/we did

Dev-Ops
=======
If you added an ENV variable, please check off that you've updated the following  
- [ ] Key & Sample value to `.env` & `sample.env` 
- [ ] GCP Secret Manager (Both development and production)
- [ ] Github Secrets (Added a development and production variable)
- [ ] Github Workflows `.github/workflows/dev.yml` & `.github/workflows/prod.yml`
- [ ] webpack-config.js

Images/Important Notes (optional):
-----------------------
* Insert any notes/issues, dependencies added or removed, or images

### CODE REVIEW

**Comment by DevanOBoyle** [comment]
I'm getting several compile time errors that all throw:  Property 'relative' does not exist on type 'IntrinsicAttributes & LinkProps & RefAttributes<HTMLAnchorElement>'. Is there another file/env variable I'm missing?

**Comment by Alperdec** [comment]
Hey Devan, can you try running yarn before starting the dev server?

**Comment by DevanOBoyle** [comment]
Running yarn before the dev server works enough for me to login and see the navbar, but once the dev server starts it throws the errors again. Design wise it looks good! Only minor thing is that the font size for the tabs looks smaller than before/in the figma.

**Review by zacktraczyk — APPROVED** [review]
Looks great

**Pull request merged**
