### PR TITLE
home component to render other views. Refactored other views into hom…

### PR DESCRIPTION
**Pull request by Alperdec**
…e/components. Hoisted tests to root view (home). Added navbar tests

Problem
=======
We needed to render all the infra Zach added into a root component

Solution
========
Created Home component.

Change Summary:
---------------
Refactored Zachs infra into /views/Home/components
Refactored tests into  /views/Home/index.test.js
Added navbar click tests to App.test.js
Added some styling to navbar

Dev-Ops
=======
If you added an ENV variable, please check off that you've updated the following  
- [ ] Key & Sample value to `.env` & `sample.env` 
- [ ] GCP Secret Manager (Both development and production)
- [ ] Github Secrets (Added a development and production variable)
- [ ] Github Workflows `.github/workflows/dev.yml` & `.github/workflows/prod.yml`
- [ ] webpack-config.js

Images/Important Notes (optional):
-----------------------
* We can add tests if needed to the components in Home/components. We'll see

### CODE REVIEW

**Review by zacktraczyk — CHANGES_REQUESTED** [review]
Looks good! If I have anything to add it is that the components folder is removed from inside `views/Home`. It makes sense to me that each component in the Home folder (`About`, `FAQs`, etc.) is all also a view itself, not a reusable component. It would be nice to avoid having another folder in the hierarchy, especially when we already have a location for reusable components.

Obviously not a big deal, but would like to know your opinion on having the `views/Home` folder contain `About`, `FAQs`, ..., `index.scss`, `index.view.tsx`. That way if views are continuously broken down into sub-views. they don't keep existing inside nested specific versions of component folders.

**Comment by Alperdec** [comment]
> Zach, I think that's a good idea and a good nuisance to avoid. I'll make the appropriate changes

**Comment by zacktraczyk** [comment]
Excellent 😎

**Review by zacktraczyk — APPROVED** [review]
Looks great

**Pull request merged**
